type BirdMintedEvent @entity {
  id: ID!
  owner: Bytes!
  tokenId: BigInt!
  imageId: BigInt!
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type GamePlayedEvent @entity {
  id: ID!
  birdId: BigInt!
  gameId: BigInt!
  score: BigInt!
  xpEarned: BigInt!
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type LevelUpEvent @entity {
  id: ID!
  birdId: BigInt!
  newLevel: BigInt!
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type PlayerRegisteredEvent @entity {
  id: ID!
  playerAddress: Bytes!
  name: String!
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type Bird @entity {
  id: ID!
  owner: Player!
  highScore: BigInt!
  xp: BigInt!
  level: BigInt!
  imageId: BigInt!
  games: [GameHistory!]! @derivedFrom(field: "bird")
  ownerIndex: BigInt!
}

type Game @entity {
  id: ID!
  gameSetupSeed: BigInt!
  pipePositions: [BigInt!]!
  questBoxPositions: [BigInt!]!
  histories: [GameHistory!]! @derivedFrom(field: "game")
}

type Player @entity {
  id: ID!
  name: String!
  highScore: BigInt!
  xp: BigInt!
  level: BigInt!
  ownedBirds: [Bird!]! @derivedFrom(field: "owner")
  games: [GameHistory!]! @derivedFrom(field: "player")
  balance: BigInt!
  tokenOfOwnerByIndex: [BigInt!]!
}

type GameHistory @entity {
  id: ID!
  bird: Bird!
  game: Game!
  player: Player!
  score: BigInt!
  xpEarned: BigInt!
  timestamp: BigInt!
}